[2023-11-06T17:10:01.144+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yahoo_finance_elt_pipeline_v1.extract_data_task manual__2023-11-06T17:09:54.166139+00:00 [queued]>
[2023-11-06T17:10:01.356+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yahoo_finance_elt_pipeline_v1.extract_data_task manual__2023-11-06T17:09:54.166139+00:00 [queued]>
[2023-11-06T17:10:01.358+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-11-06T17:10:01.444+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_data_task> on 2023-11-06 17:09:54.166139+00:00
[2023-11-06T17:10:01.520+0000] {standard_task_runner.py:57} INFO - Started process 1028 to run task
[2023-11-06T17:10:01.599+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yahoo_finance_elt_pipeline_v1', 'extract_data_task', 'manual__2023-11-06T17:09:54.166139+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/yahoo_elt_pipeline.py', '--cfg-path', '/tmp/tmpatw78cgf']
[2023-11-06T17:10:01.646+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask extract_data_task
[2023-11-06T17:10:01.940+0000] {task_command.py:416} INFO - Running <TaskInstance: yahoo_finance_elt_pipeline_v1.extract_data_task manual__2023-11-06T17:09:54.166139+00:00 [running]> on host a5d58a06784e
[2023-11-06T17:10:02.694+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mbahraoui' AIRFLOW_CTX_DAG_ID='yahoo_finance_elt_pipeline_v1' AIRFLOW_CTX_TASK_ID='extract_data_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-06T17:09:54.166139+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-06T17:09:54.166139+00:00'
[2023-11-06T17:10:04.085+0000] {logging_mixin.py:151} INFO - [*********************100%%**********************]  1 of 1 completed
[2023-11-06T17:10:05.630+0000] {logging_mixin.py:151} INFO - [*********************100%%**********************]  1 of 1 completed
[2023-11-06T17:10:07.163+0000] {logging_mixin.py:151} INFO - [*********************100%%**********************]  1 of 1 completed
[2023-11-06T17:10:08.622+0000] {logging_mixin.py:151} INFO - [*********************100%%**********************]  1 of 1 completed
[2023-11-06T17:10:09.986+0000] {logging_mixin.py:151} INFO - [*********************100%%**********************]  1 of 1 completed
[2023-11-06T17:10:11.478+0000] {logging_mixin.py:151} INFO - [*********************100%%**********************]  1 of 1 completed
[2023-11-06T17:10:12.096+0000] {logging_mixin.py:151} INFO - [*********************100%%**********************]  1 of 1 completed
[2023-11-06T17:10:12.099+0000] {multi.py:178} ERROR - 
1 Failed download:
[2023-11-06T17:10:12.113+0000] {multi.py:191} ERROR - ['FB']: Exception('%ticker%: No timezone found, symbol may be delisted')
[2023-11-06T17:10:13.451+0000] {logging_mixin.py:151} INFO - [*********************100%%**********************]  1 of 1 completed
[2023-11-06T17:10:14.972+0000] {logging_mixin.py:151} INFO - [*********************100%%**********************]  1 of 1 completed
[2023-11-06T17:10:16.261+0000] {logging_mixin.py:151} INFO - [*********************100%%**********************]  1 of 1 completed
[2023-11-06T17:10:17.612+0000] {logging_mixin.py:151} INFO - [*********************100%%**********************]  1 of 1 completed
[2023-11-06T17:10:19.171+0000] {logging_mixin.py:151} INFO - [*********************100%%**********************]  1 of 1 completed
[2023-11-06T17:10:21.069+0000] {logging_mixin.py:151} INFO - [*********************100%%**********************]  1 of 1 completed
[2023-11-06T17:10:22.533+0000] {logging_mixin.py:151} INFO - [*********************100%%**********************]  1 of 1 completed
[2023-11-06T17:10:22.757+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/yahoo_elt_pipeline.py", line 51, in extract_data
    stock_data_df.to_csv(stock_file_name, index=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 3772, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1186, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 240, in save
    with get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 737, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 600, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '../data/stock_data'
[2023-11-06T17:10:22.848+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=yahoo_finance_elt_pipeline_v1, task_id=extract_data_task, execution_date=20231106T170954, start_date=20231106T171001, end_date=20231106T171022
[2023-11-06T17:10:22.949+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 6 for task extract_data_task (Cannot save file into a non-existent directory: '../data/stock_data'; 1028)
[2023-11-06T17:10:23.042+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-06T17:10:23.512+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
